# Create a new hand
GET http://localhost:3000/api/createHand
Accept: application/json

# Get all saved hands
GET http://localhost:3000/api/getHands
Accept: application/json

# Check winner from multiple hands
GET http://localhost:3000/api/checkWinner?id=1&id=2
Accept: application/json